name: snowflake_learning
version: "1.0.0"
config-version: 2
profile: snowflake_learning
model-paths: ["models"]
seed-paths: ["seeds"]
clean-targets: ["target", "dbt_packages"]
models:
  snowflake_learning:
    staging:
      +schema: staging
      +materialized: view
    marts:
      +schema: marts
      +materialized: table
seeds:
  snowflake_learning:
    +schema: raw