services:
  airflow:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: snowflake-dbt-airflow
    command: airflow standalone
    env_file:
      - .env
    environment:
      AIRFLOW_HOME: /opt/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
      DBT_PROFILES_DIR: /opt/airflow/dbt
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./dbt:/opt/airflow/dbt
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./keys:/opt/airflow/keys:ro
    restart: unless-stopped